### ISSUE TITLE
Youtube Ads intermittently play instead of visited video

### ISSUE THREAD

**Issue by kirkins** [MoonchildProductions/Pale-Moon#1014]
Anyone notice issues when Youtube Ads play?

1. Skip button disappears when clicked but video keeps playing.
2. After video finishes, real video doesn't start, just play button as if ad was main video.
3. Doesn't always happen but happens often.

![untitled](https://cloud.githubusercontent.com/assets/9503662/24841857/f891e0a6-1d5b-11e7-825f-c0f5bb9d0f7f.png)

**Comment by adisib** [comment]
Also noticed. Was wondering if it was related to my Youtube HD script, but it doesn't seem like that is the case. It started happening around late March for me, which coincidentally is around when Pale Moon 27.2.1 was released. I don't see any media changes in the release notes; are there any minor unmentioned media changes for that release, or is it YouTube who did a change causing the problem?

**Comment by kirkins** [comment]
I think ussual pattern is glitch happens, refresh see another ad, click again, works.

**Comment by wolfbeast** [comment]
I haven't noticed it myself, but it's likely related to the stuff we're still working on. Our media playback, especially through MSE, is still a work in progress and things like skipping, jumping to specific time points, etc. can glitch in release versions. This will likely be resolved in one of the batches of patches that are being landed by Travis (if not already solved). Closing this issue since it's too generic, we're already aware of quirks, and it's being worked on.

**Comment by adisib** [comment]
On 27.4, I've just encountered youtube loading the ad as the video after clicking the skip ad button, so the new media code has not resolved this.

**Comment by wolfbeast** [comment]
I'm definitely not able to reproduce this myself. Do you have a few links where this occurs for you? Are you using the default settings?

**Comment by kirkins** [comment]
I was originally told the error shouldn't or that it didn't exist. 

It was still an issue when I stopped using Palemoon and was one of my reasons for stopping. I'd test it now but I don't have arch installed ATM.

**Comment by kirkins** [comment]
@adisib if you're looking for a really fast open-source browser you might want to check this out

https://github.com/qutebrowser/qutebrowser

**Comment by adisib** [comment]
Unfortunately, I was never able to find any way to reliably reproduce it. It is too early to say whether it occurs more or less frequently than it has before. I am using default media settings.

I understand there really isn't anything you can do if you can't reproduce it or even confirm if the media code is related. If I can get any useful details, I will make sure to let you know.

**Comment by wolfbeast** [comment]
@kirkins If you are no longer able to meaningfully contribute to Pale Moon issues/discussion because you are no longer a user, then kindly do not comment as it serves only to distract from the problem at hand, and certainly do not use it as a vessel to advertise something else.

**Comment by adisib** [comment]
I haven't been able to get much information, because this happens so infrequently. But I have noticed that whenever this happens, I can find a "NotFoundError: Node was not found [annotations_module](https://www.youtube.com/yts/jsbin/player-vflTof4g1/en_US/annotations_module.js).js:481:0" message in the devtools console, and never see that message otherwise.

This doesn't happen often enough for me to be completely sure of that, but it seems like it is probably a javascript issue where specific advertisements are handling annotation code in such a way as Pale Moon doesn't like the javascript and throws an error, preventing youtube from destroying the advertisement and moving on to the actual video. The particular code line involves cleaning up resources, and I've noticed that it had often happened multiple times in a row on some videos (because I kept getting the same advertisements that would use the same annotations) and it happens so rare for me now, likely because I am being served different advertisements. This would also explain why you never ran into the problem, as you would be served different advertisements as well.

If someone is interested in tackling this bug, you should probably look into javascript issues, rather than media issues.

**Comment by wolfbeast** [comment]
If the node was not found in the annotations script, then that means the script is expecting a DOM node to be present (which may have been blocked by the user, e.g. with script/ad blocking extensions, or simply not created when it should have been which would be a YT script error). I don't think there is anything that can be done on our end here. Closing this for now.
