### ISSUE TITLE
Error: call to Function() blocked by CSP on GitHub

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1089]
It seems that today GitHub made some server-side changes that result to its partial nonoperability in Pale Moon. 

Error console shows the following CSP error:

`Error: call to Function() blocked by CSP frameworks-b656af906df0ec252f7683ae76db8ed358bf5b309bd5781fc467ae3c1d571c2a.js:1:6948`

And only setting `security.csp.enable` to `false` helps to restore full functionality.

Mozregression points to [this pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=506facea63169a29e04eb140663da1730052db64&tochange=b3ec8a3373e8faca26c39e9ff577a2d4f8b6927a), ~~I think [Bug 1298505](https://bugzilla.mozilla.org/show_bug.cgi?id=1298505) is under suspicion.~~

**Comment by janekptacijarabaci** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1114580 ?

**Comment by wolfbeast** [comment]
As far as I can tell, the problem is specific coding on GitHub.
Using `new Function()` is not permitted in CSP restricted document types, because it would allow dynamically-generated code.
See also: https://wiki.mozilla.org/Security/CSP/Specification#Base_Restrictions

Yet, the framework script uses `t.exports=new Function("return this")()},{}]` and as a result, Pale Moon blocks it. No exports means no functioning framework controls in the GitHub UI.

**Comment by wolfbeast** [comment]
Confirmed a CSP implementation issue on GitHub:

Spec says:

>The following JavaScript execution sinks are gated on the "unsafe-eval" source expression:
> ...
>    Function()

https://www.w3.org/TR/CSP/#directive-script-src

GitHub CSP isn't including `unsafe-eval` in their `script-src` directive. As such, `new Function()` isn't allowed.

**Comment by wolfbeast** [comment]
I'm not sure why the mozregression range would fix this unless it is an unintended side-effect of one of the changes in Firefox in that range. None of the bugs listed there stand out as specifically addressing or touching the Function() code.

**Comment by wolfbeast** [comment]
Looks like this was fixed on the server side.

**Comment by wolfbeast** [comment]
Reopened this - I think I made a mistake testing; this is still an issue.

**Comment by wolfbeast** [comment]
To verify, I've short-circuited the security check on new Function() in the constructor in a local build. This solves the issue so it's clearly the problem, here. Unfortunately, this is clearly a spec compliance issue if we don't enforce this, so GitHub will have to fix it to solve. On the FF side, this seems to have been broken and should probably be reported.

**Comment by wolfbeast** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1363298 on the Mozilla side for the Firefox spec compliance issue.

**Comment by JustOff** [comment]
Here is even shorter [regression range from mozilla-inbound](https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=b3276dc9d5b1282e5c80b3fffff616da92d6bfae&tochange=41d8277af19246308bdf51bf0cd60da3498681b1), but still can't figure where exactly the problem arose.

**Comment by SeaHOH** [comment]
Google Chrome was loaded the framework too.

**Comment by wolfbeast** [comment]
At this point it seems likely that GitHub uses an ES6 symbols shim that is incompatible with their CSP policy. Later Firefox versions won't hit the offending constructor code because the symbol implementation is as their framework code expects. If these assumptions are correct, then porting Bug 1114580 (and possible dependencies) would solve the interop for us by dodging the CSP-incompatible code, but ultimately it remains a bug in GitHub's implementation.

**Comment by JustOff** [comment]
> [Bug 1114580](https://bugzilla.mozilla.org/show_bug.cgi?id=1114580) ?

@janekptacijarabaci, how did you guess? :alien:

**Comment by JustOff** [comment]
It seems that GitHub has fixed this issue.

**Comment by wolfbeast** [comment]
Yup, looks like it.
I just got a reply from GH support that a fix had been deployed.
Closing.

**Comment by janekptacijarabaci** [comment]
@JustOff 
I looked into the source code (`frameworks-*.js` and this bug). But it was a conjecture (AFAIK) :-)

**Comment by wolfbeast** [comment]
@janekptacijarabaci I'm not sure what you think was conjecture. The script did make this call (I verified the location in the script at the time) and did hit our spec compliant security. I don't know what they changed to take a different code path, but if the call is still in there, then they clearly worked around it another way instead of not using the constructor.

**Comment by wolfbeast** [comment]
For the record, I did look into this a bit more to see what might be the difference with Firefox that tripped this up.
At this point it seems likely that GitHub uses an ES6 symbols shim that was incompatible with their CSP policy. Later Firefox versions didn't hit the offending constructor code because the ES6 symbols implementation is as their framework code expects, so it never lands in the shim with the offending code (that Firefox would also trip over). 

If these assumptions are correct, then porting Bug 1114580 (and possible dependencies) would also have solved the interop for us by dodging the CSP-incompatible code (by no longer making use of the shim code), but ultimately it remained a bug in GitHub's implementation, just one that wasn't hit by later Firefox code.
